### ISSUE TITLE
Installing realsense on rpi4 help

### ISSUE THREAD

**Issue by GOBish** [samhoff20/Realsense-Object-Detection-Public#3]
thanks for sharing all your work! I really appreciate it!
Can you go over the steps of how you installed realsense on the rpi4? I am having trouble and cant get it working. 
Thanks!

**Comment by samhoff20** [comment]
I didn't document my steps, but could you tell me a little more about the issue your having? Maybe I can still be of some help.

**Comment by GOBish** [comment]
I downloaded the latest version here:
https://github.com/IntelRealSense/librealsense/releases
(2.31.0) tar.gz
made a build folder, and tried building it with cmake.
I am running raspbian.

**Comment by samhoff20** [comment]
Try looking at this thread and see if it helps: https://github.com/IntelRealSense/librealsense/issues/4272

**Comment by GOBish** [comment]
yeah, I haven't gotten that to work either. I think partly it may be a 4GB version of RPi4 issue. what are you using?

**Comment by samhoff20** [comment]
I'm using the 4gb as well. I'm not home anymore but I would look further into if you've used all the right flags in cmake.

**Comment by GOBish** [comment]
Thanks for all the help - finally got realsense working on the RPi.
Only issue now is it can't find the pyrealsense2 import.
I did install with DBUILD_PYTHON_BINDINGS=true
did you have to do anything else after that?

**Comment by samhoff20** [comment]
I don't remember, sorry. I should have took notes.

**Comment by GOBish** [comment]
Got it working, had to make some path changes to bashrc
